<script lang="ts" module>
  export type ThemeInitProps = Record<string, never>;
</script>

<script lang="ts">
  import { applyInitialTheme, createHeadSnippet } from '@layerstack/tailwind';
  import { browser } from '@layerstack/utils/env';

  import { getSettings } from './settingsState.svelte.js';

  const settings = getSettings();

  // Inlined into `<head>` so the stored theme is applied before first paint, avoiding a flash of
  // the wrong theme.  Only effective when the markup is served by the server.
  const headSnippet = createHeadSnippet(settings.themes.dark);

  // A `<script>` inserted through `{@html}` is never executed by the browser, so on a client-only
  // app (`ssr = false`) the snippet above is inert.  Apply the same thing directly — this runs
  // during init, before the app has painted.
  if (browser) {
    applyInitialTheme(settings.themes.dark);
  }
</script>

<svelte:head>
  <!-- eslint-disable-next-line svelte/no-at-html-tags -- generated by `@layerstack/tailwind` -->
  {@html headSnippet}
</svelte:head>
